const filesMap = {
  "16px": {
    "title": "16px",
    "files": [
      "calculator",
      "cassette",
      "cog",
      "dopamine_3",
      "folder",
      "folder_alt",
      "headphones",
      "heart",
      "keyboard",
      "lightbulb",
      "link",
      "magnet",
      "media-player-classic",
      "mp3-tag",
      "palette",
      "photoshop",
      "photoshop_boxless",
      "photoshop_solid",
      "ppsspp",
      "screen-to-gif",
      "steam_boxless",
      "sublime-text",
      "sublime-text_boxless",
      "terminal",
      "trash",
      "treesize",
      "visual-studio",
      "visual-studio-code",
      "windows-media-player"
    ]
  },
  "16px/outline": {
    "title": "16px (outline)",
    "files": [
      "circle-cross",
      "circle-divide",
      "circle-minus",
      "circle-pause",
      "circle-play",
      "circle-plus",
      "compact-disc",
      "download",
      "film",
      "flag",
      "floppy_disk",
      "globe",
      "joystick",
      "monitor",
      "multimedia",
      "recycle-bin_empty",
      "recycle-bin_full",
      "tools",
      "trash_bin",
      "user",
      "users"
    ]
  },
  "32px": {
    "title": "32px",
    "files": [
      "afterburner",
      "audacity",
      "chrome",
      "firefox",
      "fullscreenizer",
      "globe",
      "globe_alt",
      "keyboard",
      "microphone",
      "notepad",
      "notepad_with_pencil",
      "qBittorrent",
      "qBittorrent_boxless",
      "qBittorrent_solid",
      "speaker",
      "windows_11",
      "windows_8",
      "xpadder"
    ]
  }
};
