const filesMap = {
  '16px': {
    title: '16px',
    files: [
      'aimp',
      'archive',
      'backup',
      'brightness',
      'calculator',
      'camera',
      'cassette',
      'chrome',
      'cog',
      'cog_alt',
      'dopamine_3',
      'downloads',
      'folder',
      'folder_alt',
      'gog',
      'headphones',
      'heart',
      'joystick',
      'keyboard',
      'lightbulb',
      'link',
      'magnet',
      'media-player-classic',
      'mp3-tag',
      'palette',
      'photoshop',
      'photoshop_boxless',
      'photoshop_solid',
      'ppsspp',
      'reload',
      'screen-to-gif',
      'steam_boxless',
      'sublime-text',
      'sublime-text_boxless',
      'terminal',
      'trash',
      'trash_empty',
      'trash_full',
      'trash_half',
      'treesize',
      'usb',
      'usb_outline',
      'visual-studio',
      'visual-studio-code',
      'windows-media-player',
    ],
  },
  '16px/outline': {
    title: '16px (outline)',
    files: [
      'circle-cross',
      'circle-divide',
      'circle-minus',
      'circle-pause',
      'circle-play',
      'circle-plus',
      'compact-disc',
      'compact-disc_old',
      'download',
      'film',
      'flag',
      'floppy_disk',
      'globe',
      'hibernate',
      'joystick',
      'monitor',
      'multimedia',
      'recycle-bin_empty',
      'recycle-bin_full',
      'shutdown',
      'tools',
      'trash_bin',
      'user',
      'users',
    ],
  },
  '32px': {
    title: '32px',
    files: [
      'afterburner',
      'audacity',
      'chrome',
      'firefox',
      'fullscreenizer',
      'gcn',
      'globe',
      'globe_alt',
      'keyboard',
      'microphone',
      'notepad',
      'notepad_with_pencil',
      'python',
      'python_outline',
      'qBittorrent',
      'qBittorrent_alt',
      'qBittorrent_boxless',
      'qBittorrent_solid',
      'speaker',
      'windows_8',
      'windows_11',
      'xpadder',
    ],
  },
};
